package com.mycompany.interfaz;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.mycompany.dao.ProductoDAO;
import com.mycompany.dominio.Producto;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David CE
 */
public class DialogBuscarProducto extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogBuscarProducto.class.getName());

    private ProductoDAO productoDAO = new ProductoDAO();
    private Producto productoSeleccionado;

    /**
     * Creates new form DialogCrearFactura
     */
    public DialogBuscarProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal ? java.awt.Dialog.ModalityType.APPLICATION_MODAL : java.awt.Dialog.ModalityType.MODELESS);
        initComponents();
        // 1. APLICAR ESTILOS VISUALES
        configurarEstilos();

        // 2. CONFIGURAR COLUMNAS DE LA TABLA
        configurarColumnas();

        // 3. AJUSTAR TAMAÑO Y POSICIÓN
        pack();
        setLocationRelativeTo(parent);

        // Cargar todos los productos al abrir
        cargarProductos("");
    }

    private void configurarColumnas() {
        // Código (100px)
        tblResultados.getColumnModel().getColumn(0).setPreferredWidth(100);
        tblResultados.getColumnModel().getColumn(0).setMaxWidth(120);

        // Descripción (Ancho variable)
        tblResultados.getColumnModel().getColumn(1).setPreferredWidth(300);

        // Precio (100px)
        tblResultados.getColumnModel().getColumn(2).setPreferredWidth(100);
        tblResultados.getColumnModel().getColumn(2).setMaxWidth(120);

        // IVA (80px)
        tblResultados.getColumnModel().getColumn(3).setPreferredWidth(80);
        tblResultados.getColumnModel().getColumn(3).setMaxWidth(100);

        tblResultados.setRowHeight(30);
    }

    private void configurarEstilos() {
        // Fondo
        panelPrincipal.setBackground(Estilos.COLOR_FONDO_MENTA);

        // Buscador
        Estilos.configurarBarraBusqueda(txtBuscar);
        txtBuscar.putClientProperty(com.formdev.flatlaf.FlatClientProperties.PLACEHOLDER_TEXT, "Buscar por código o descripción...");

        // Botones
        Estilos.configurarBotonAccion(btnBuscar);
        Estilos.configurarBotonAccion(btnAceptar);
        Estilos.configurarBotonAccion(btnCancelar);

        // Icono Lupa
        FlatSVGIcon iconSearch = new FlatSVGIcon("img/search.svg", 18, 18);
        iconSearch.setColorFilter(new FlatSVGIcon.ColorFilter(c -> java.awt.Color.WHITE));
        btnBuscar.setIcon(iconSearch);
        btnBuscar.setText("");

        // Tabla
        Estilos.configurarTabla(tblResultados, panelCentral);
    }

    private void cargarProductos(String busqueda) {
        // Obtenemos todos los productos (aquí podrías filtrar en el DAO si la lista es enorme)
        // Para simplificar, traemos todos y filtramos, o usamos un método buscarPorNombre en DAO si lo creaste.
        // Asumimos que ProductoDAO tiene listarTodos().
        List<Producto> lista = productoDAO.listarTodos();

        DefaultTableModel modelo = (DefaultTableModel) tblResultados.getModel();
        modelo.setRowCount(0);

        String filtro = busqueda.toLowerCase().trim();

        for (Producto p : lista) {
            // Filtrado simple en memoria (si tienes buscarPorNombre en DAO úsalo mejor)
            boolean coincide = p.getDescription().toLowerCase().contains(filtro)
                    || p.getCode().toLowerCase().contains(filtro);

            if (coincide || filtro.isEmpty()) {
                modelo.addRow(new Object[]{
                    p.getCode(),
                    p.getDescription(),
                    p.getUnitPrice() + " €",
                    p.getTaxPercent() + " %",
                    p // Guardamos el objeto entero en la columna oculta (opcional) o usamos el índice
                });
            }
        }
    }
    
    public Producto getProductoSeleccionado() {
        return productoSeleccionado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal = new javax.swing.JPanel();
        panelBusqueda = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        panelCentral = new javax.swing.JScrollPane();
        tblResultados = new javax.swing.JTable();
        panelBotones = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btnCancelar = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btnAceptar = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva Factura");
        setModal(true);
        setResizable(false);

        panelPrincipal.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        panelPrincipal.setLayout(new java.awt.BorderLayout());

        panelBusqueda.setOpaque(false);
        panelBusqueda.setLayout(new java.awt.GridBagLayout());

        txtBuscar.addActionListener(this::txtBuscarActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        panelBusqueda.add(txtBuscar, gridBagConstraints);

        btnBuscar.addActionListener(this::btnBuscarActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelBusqueda.add(btnBuscar, gridBagConstraints);

        panelPrincipal.add(panelBusqueda, java.awt.BorderLayout.PAGE_START);

        panelCentral.setMinimumSize(new java.awt.Dimension(800, 300));
        panelCentral.setPreferredSize(new java.awt.Dimension(800, 300));

        tblResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Descripción", "Precio", "Tipo IVA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        panelCentral.setViewportView(tblResultados);

        panelPrincipal.add(panelCentral, java.awt.BorderLayout.CENTER);

        panelBotones.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 0, 0, 0));
        panelBotones.setOpaque(false);
        panelBotones.setLayout(new javax.swing.BoxLayout(panelBotones, javax.swing.BoxLayout.LINE_AXIS));
        panelBotones.add(filler4);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        panelBotones.add(btnCancelar);
        panelBotones.add(filler5);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(this::btnAceptarActionPerformed);
        panelBotones.add(btnAceptar);
        panelBotones.add(filler3);

        panelPrincipal.add(panelBotones, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        cargarProductos(txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        int fila = tblResultados.getSelectedRow();
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un producto.");
            return;
        }

        // Recuperamos el código (columna 0) para buscarlo en la lista original 
        // O recuperamos el objeto si lo tenemos mapeado.
        // Haremos la estrategia de buscar en la lista cargada actual:
        String codigo = (String) tblResultados.getValueAt(fila, 0);

        // Buscamos en BBDD o lista para devolver el objeto exacto
        // (Forma rápida: iterar la lista actual. Forma correcta: DAO getByCode)
        List<Producto> lista = productoDAO.listarTodos();
        for (Producto p : lista) {
            if (p.getCode().equals(codigo)) {
                this.productoSeleccionado = p;
                break;
            }
        }
        this.dispose();
        }//GEN-LAST:event_btnAceptarActionPerformed
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.
        dispose();    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        cargarProductos(txtBuscar.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogBuscarProducto dialog = new DialogBuscarProducto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JScrollPane panelCentral;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTable tblResultados;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

}
