/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.interfaz;

/**
 *
 * @author DavidCe
 */
public class PanelFacturas extends javax.swing.JPanel {

    /**
     * Creates new form PanelClientes
     */
    public PanelFacturas() {
        initComponents();

        // --- 1. TABLA
        // --- APLICAR ESTILO A LA TABLA ---
        Estilos.configurarTabla(tblInvoices, jScrollPaneCenter);

        // --- DEFINIR ANCHOS DE COLUMNAS ---
// --- DEFINIR ANCHOS DE COLUMNAS (Total aprox: 800-900px) ---
        // 0. Nº Factura
        tblInvoices.getColumnModel().getColumn(0).setPreferredWidth(90);
        tblInvoices.getColumnModel().getColumn(0).setMaxWidth(100);

        // 1. Cliente (Le damos un poco más de espacio)
        tblInvoices.getColumnModel().getColumn(1).setPreferredWidth(180);

        // 2. Descripción (Reducimos un poco porque ya no tiene la fecha dentro)
        tblInvoices.getColumnModel().getColumn(2).setPreferredWidth(200);

        // 3. Estado
        tblInvoices.getColumnModel().getColumn(3).setPreferredWidth(80);

        // 4. Total
        tblInvoices.getColumnModel().getColumn(4).setPreferredWidth(80);

        // 5. Fecha Emisión
        tblInvoices.getColumnModel().getColumn(5).setPreferredWidth(120);

        // Bloquear reordenamiento
        tblInvoices.getTableHeader().setReorderingAllowed(false);

        // --- 2. BARRA DE BÚSQUEDA
        // --- APLICAR ESTILO A LA BARRA DE BÚSQUEDA ---
        Estilos.configurarBarraBusqueda(txtSearch);
        txtSearch.putClientProperty(com.formdev.flatlaf.FlatClientProperties.PLACEHOLDER_TEXT, "Buscar Factura por Nº");

        // --- 3. BOTONES
        // --- APLICAR ESTILO A LOS BOTONES ---
        // Creamos una lista con todos los botones para aplicarles el estilo "Píldora Negra" de golpe
        javax.swing.JButton[] botonesAccion = {
            btnCreateInvoice, // Añadir Cliente
            btnInvoiceDetails, // Editar
            btnVerifyAEAT // Borrar
        };

        for (javax.swing.JButton btn : botonesAccion) {
            Estilos.configurarBotonAccion(btn);
        }

        // Botón Home como Icono
        com.formdev.flatlaf.extras.FlatSVGIcon homeIcon = new com.formdev.flatlaf.extras.FlatSVGIcon("img/home_Icon.svg", 32, 32);
        // Usamos Color.BLACK (o Color.decode("#111111") para negro suave)
        homeIcon.setColorFilter(new com.formdev.flatlaf.extras.FlatSVGIcon.ColorFilter(color -> java.awt.Color.BLACK));
        btnHome.setIcon(homeIcon);
        btnHome.setText("");
        // Estilo "invisible" para que solo se vea el icono
        btnHome.setContentAreaFilled(false);
        btnHome.setBorderPainted(false);
        btnHome.setFocusPainted(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        // Añadir icono a los botones
        setIconoBlanco(btnInvoiceDetails, "img/details_Icon.svg");
        setIconoBlanco(btnVerifyAEAT, "img/check_Icon.svg");

        // --- CONFIGURACIÓN BOTÓN CREAR FACTURA ---
        // 1. Cargar el icono SVG (Tamaño 20x20)
        com.formdev.flatlaf.extras.FlatSVGIcon iconAdd = new com.formdev.flatlaf.extras.FlatSVGIcon("img/add_Icon.svg", 20, 20);

        // 2. Pintarlo de BLANCO (porque el botón es negro)
        iconAdd.setColorFilter(new com.formdev.flatlaf.extras.FlatSVGIcon.ColorFilter(c -> java.awt.Color.WHITE));

        // 3. Asignarlo al botón
        btnCreateInvoice.setIcon(iconAdd);

        // 4. Ajustes visuales
        btnCreateInvoice.setIconTextGap(10); // Espacio entre el (+) y el texto
        btnCreateInvoice.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT); // Texto a la derecha del icono

        // Asegurarnos de que el texto esté centrado verticalmente
        btnCreateInvoice.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);

        // Ajustes finales de texto y márgenes
        javax.swing.JButton[] botones = {btnInvoiceDetails, btnVerifyAEAT};
        for (javax.swing.JButton btn : botones) {
            btn.setIconTextGap(15);
            btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            // Ajusta este margen si quieres los botones más o menos anchos
            btn.setMargin(new java.awt.Insets(10, 15, 10, 15));
        }

        // --- 4. CARGAR DATOS DE FACTURAS DE LA BASE DE DATOS ---
        cargarTablaFacturas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelCenter = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnCreateInvoice = new javax.swing.JButton();
        jScrollPaneCenter = new javax.swing.JScrollPane();
        tblInvoices = new javax.swing.JTable();
        jPanelRight = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnInvoiceDetails = new javax.swing.JButton();
        btnVerifyAEAT = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setBackground(new java.awt.Color(160, 238, 204));
        setLayout(new java.awt.BorderLayout());

        jPanelCenter.setBackground(new java.awt.Color(160, 238, 204));
        jPanelCenter.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelCenter.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 15, 10);
        jPanelCenter.add(txtSearch, gridBagConstraints);

        btnCreateInvoice.setText("Crear Factura");
        btnCreateInvoice.addActionListener(this::btnCreateInvoiceActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 15, 10);
        jPanelCenter.add(btnCreateInvoice, gridBagConstraints);

        jScrollPaneCenter.setOpaque(false);

        tblInvoices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nº", "Nº Cliente", "Descripción", "Estado", "Total Factura", "Fecha emisión"
            }
        ));
        jScrollPaneCenter.setViewportView(tblInvoices);
        if (tblInvoices.getColumnModel().getColumnCount() > 0) {
            tblInvoices.getColumnModel().getColumn(0).setResizable(false);
            tblInvoices.getColumnModel().getColumn(1).setResizable(false);
            tblInvoices.getColumnModel().getColumn(2).setResizable(false);
            tblInvoices.getColumnModel().getColumn(3).setResizable(false);
            tblInvoices.getColumnModel().getColumn(4).setResizable(false);
            tblInvoices.getColumnModel().getColumn(5).setResizable(false);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelCenter.add(jScrollPaneCenter, gridBagConstraints);

        add(jPanelCenter, java.awt.BorderLayout.CENTER);

        jPanelRight.setOpaque(false);
        jPanelRight.setPreferredSize(new java.awt.Dimension(200, 0));
        jPanelRight.setLayout(new java.awt.GridBagLayout());

        btnHome.setText("HOME");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 10);
        jPanelRight.add(btnHome, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 1.0;
        jPanelRight.add(filler1, gridBagConstraints);

        btnInvoiceDetails.setText("Datos Factura");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 10);
        jPanelRight.add(btnInvoiceDetails, gridBagConstraints);

        btnVerifyAEAT.setText("Verificar AEAT");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 10);
        jPanelRight.add(btnVerifyAEAT, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weighty = 1.0;
        jPanelRight.add(filler2, gridBagConstraints);

        add(jPanelRight, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateInvoiceActionPerformed
        // 1. Obtener la ventana principal (JFrame) para que sea el "padre" del diálogo
        // Esto es necesario para que el diálogo sepa centrarse y bloquear la ventana de atrás (modal)
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        java.awt.Frame parentFrame = null;

        if (parentWindow instanceof java.awt.Frame) {
            parentFrame = (java.awt.Frame) parentWindow;
        }

        // 2. Crear el Diálogo (true = modal, bloquea la ventana de atrás)
        DialogCrearFactura dialog = new DialogCrearFactura(parentFrame, true);

        // 3. Mostrarlo
        // El código se detendrá aquí hasta que el usuario cierre el diálogo
        dialog.setVisible(true);

        // AL VOLVER DEL DIÁLOGO, REFRESCAMOS:
        cargarTablaFacturas();
    }//GEN-LAST:event_btnCreateInvoiceActionPerformed

    private void setIconoBlanco(javax.swing.JButton btn, String rutaSvg) {
        com.formdev.flatlaf.extras.FlatSVGIcon icon = new com.formdev.flatlaf.extras.FlatSVGIcon(rutaSvg, 20, 20);
        // Fuerza el color blanco
        icon.setColorFilter(new com.formdev.flatlaf.extras.FlatSVGIcon.ColorFilter(color -> java.awt.Color.WHITE));
        btn.setIcon(icon);
    }

    // MÉTODO PARA CARGAR LAS FACTURAS
    public void cargarTablaFacturas() {
        // 1. Limpiar la tabla actual
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblInvoices.getModel();
        model.setRowCount(0);

        // 2. Obtener datos
        com.mycompany.dao.FacturaDAO dao = new com.mycompany.dao.FacturaDAO();
        java.util.List<com.mycompany.dominio.Factura> lista = dao.listarTodas();

        java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

        // 3. Rellenar filas
        for (com.mycompany.dominio.Factura f : lista) {

            // A. Nº Factura
            String numeroFormateado = f.getSeries() + "-" + String.format("%04d", f.getNumber());

            // B. Cliente
            String nombreCliente = "Desconocido";
            if (f.getCliente() != null) {
                nombreCliente = f.getCliente().getFiscalName();
            }

            // C. Descripción
            String descripcion = "FACTURA GENERAL";
            if (f.getSeries() != null) {
                if (f.getSeries().equalsIgnoreCase("F")) {
                    descripcion = "FACTURA COMPLETA";
                } else if (f.getSeries().equalsIgnoreCase("R")) {
                    descripcion = "FACTURA RECTIFICATIVA";
                }
            }

            // D. Estado (CAMBIO SOLICITADO)
            String estado = "PENDIENTE";
            // Si hay UUID, consideramos que está enviada correctamente
            if (f.getFiskalyUuid() != null && !f.getFiskalyUuid().isEmpty()) {
                estado = "ENVIADA";
            }

            // E. Fecha de Emisión (NUEVA COLUMNA)
            String fechaTexto = "";
            if (f.getDate() != null) {
                fechaTexto = f.getDate().format(formatter);
            } else if (f.getCreatedAt() != null) {
                // Fallback por si date es nulo (usamos created_at)
                fechaTexto = f.getCreatedAt().format(formatter);
            }

            // F. Añadir fila (AHORA CON 6 ELEMENTOS)
            model.addRow(new Object[]{
                numeroFormateado, // 0. Nº
                nombreCliente, // 1. Cliente
                descripcion, // 2. Descripción
                estado, // 3. Estado (ENVIADA / PENDIENTE)
                String.format("%.2f €", f.getTotalAmount()), // 4. Total
                fechaTexto // 5. Fecha Emisión
            });
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateInvoice;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnInvoiceDetails;
    private javax.swing.JButton btnVerifyAEAT;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JScrollPane jScrollPaneCenter;
    private javax.swing.JTable tblInvoices;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    // Método puente para acceder al botón Home desde fuera
    public javax.swing.JButton getBtnHome() {
        return btnHome;
    }
}
