/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.interfaz;

import com.mycompany.dao.ProductoDAO;
import com.mycompany.dominio.Producto;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author DavidCe
 */
public class PanelProductos extends javax.swing.JPanel {

    private ProductoDAO productoDAO = new ProductoDAO(); // Instancia del DAO
    private TableRowSorter<TableModel> sorter; //Sirve para filtrar en la búsqueda dinámica del producto

    /**
     * Creates new form PanelClientes
     */
    public PanelProductos() {
        initComponents();

        // --- 1. TABLA
        // --- APLICAR ESTILO A LA TABLA ---
        Estilos.configurarTabla(tblProducts, jScrollPaneCenter);

        // --- DEFINIR ANCHOS DE COLUMNAS ---
        // Código Producto: 90px (Tamaño ideal para números de 4-5 cifras)
        tblProducts.getColumnModel().getColumn(0).setPreferredWidth(90);
        tblProducts.getColumnModel().getColumn(0).setMaxWidth(110);

        // Descripción: 250px
        tblProducts.getColumnModel().getColumn(1).setPreferredWidth(450);

        // Precio: 90px 
        tblProducts.getColumnModel().getColumn(2).setPreferredWidth(50);

        // Tipo IVA: 90 px
        tblProducts.getColumnModel().getColumn(3).setPreferredWidth(50);

        // Bloquear reordenamiento
        tblProducts.getTableHeader().setReorderingAllowed(false);

        // --- 2. BARRA DE BÚSQUEDA
        // --- APLICAR ESTILO A LA BARRA DE BÚSQUEDA ---
        Estilos.configurarBarraBusqueda(txtSearch);
        txtSearch.putClientProperty(com.formdev.flatlaf.FlatClientProperties.PLACEHOLDER_TEXT, "Buscar Producto por Descripción o Código");

        // --- 3. BOTONES
        // --- APLICAR ESTILO A LOS BOTONES ---
        // Creamos una lista con todos los botones para aplicarles el estilo "Píldora Negra" de golpe
        javax.swing.JButton[] botonesAccion = {
            btnAddProduct, // Añadir Cliente
            btnEditProduct, // Editar
            btnDeleteProduct // Borrar
        };

        for (javax.swing.JButton btn : botonesAccion) {
            Estilos.configurarBotonAccion(btn);
        }

        // Botón Home como Icono
        com.formdev.flatlaf.extras.FlatSVGIcon homeIcon = new com.formdev.flatlaf.extras.FlatSVGIcon("img/home_Icon.svg", 32, 32);
        // Usamos Color.BLACK (o Color.decode("#111111") para negro suave)
        homeIcon.setColorFilter(new com.formdev.flatlaf.extras.FlatSVGIcon.ColorFilter(color -> java.awt.Color.BLACK));
        btnHome.setIcon(homeIcon);
        btnHome.setText("");
        // Estilo "invisible" para que solo se vea el icono
        btnHome.setContentAreaFilled(false);
        btnHome.setBorderPainted(false);
        btnHome.setFocusPainted(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        // Añadir icono a los botones
        setIconoBlanco(btnEditProduct, "img/edit_icon.svg");
        setIconoBlanco(btnDeleteProduct, "img/delete_icon.svg");

        // --- CONFIGURACIÓN BOTÓN AÑADIR PRODUCTO ---
        // 1. Cargar el icono SVG (Tamaño 20x20)
        com.formdev.flatlaf.extras.FlatSVGIcon iconAdd = new com.formdev.flatlaf.extras.FlatSVGIcon("img/add_Icon.svg", 20, 20);

        // 2. Pintarlo de BLANCO (porque el botón es negro)
        iconAdd.setColorFilter(new com.formdev.flatlaf.extras.FlatSVGIcon.ColorFilter(c -> java.awt.Color.WHITE));

        // 3. Asignarlo al botón
        btnAddProduct.setIcon(iconAdd);

        // 4. Ajustes visuales
        btnAddProduct.setIconTextGap(10); // Espacio entre el (+) y el texto
        btnAddProduct.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT); // Texto a la derecha del icono

        // Asegurarnos de que el texto esté centrado verticalmente
        btnAddProduct.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);

        // Ajustes finales de texto y márgenes
        javax.swing.JButton[] botones = {btnEditProduct, btnDeleteProduct};
        for (javax.swing.JButton btn : botones) {
            btn.setIconTextGap(15);
            btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            // Ajusta este margen si quieres los botones más o menos anchos
            btn.setMargin(new java.awt.Insets(10, 15, 10, 15));
        }

        cargarProductos(""); // <--- CARGA INICIAL
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelCenter = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnAddProduct = new javax.swing.JButton();
        jScrollPaneCenter = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        jPanelRight = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnEditProduct = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnDeleteProduct = new javax.swing.JButton();

        setBackground(new java.awt.Color(160, 238, 204));
        setLayout(new java.awt.BorderLayout());

        jPanelCenter.setBackground(new java.awt.Color(160, 238, 204));
        jPanelCenter.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelCenter.setLayout(new java.awt.GridBagLayout());

        txtSearch.addActionListener(this::txtSearchActionPerformed);
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 15, 10);
        jPanelCenter.add(txtSearch, gridBagConstraints);

        btnAddProduct.setText("Añadir Producto");
        btnAddProduct.addActionListener(this::btnAddProductActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 15, 10);
        jPanelCenter.add(btnAddProduct, gridBagConstraints);

        jScrollPaneCenter.setOpaque(false);

        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Descripción", "Precio", "Tipo IVA"
            }
        ));
        jScrollPaneCenter.setViewportView(tblProducts);
        if (tblProducts.getColumnModel().getColumnCount() > 0) {
            tblProducts.getColumnModel().getColumn(0).setResizable(false);
            tblProducts.getColumnModel().getColumn(1).setResizable(false);
            tblProducts.getColumnModel().getColumn(2).setResizable(false);
            tblProducts.getColumnModel().getColumn(3).setResizable(false);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelCenter.add(jScrollPaneCenter, gridBagConstraints);

        add(jPanelCenter, java.awt.BorderLayout.CENTER);

        jPanelRight.setOpaque(false);
        jPanelRight.setPreferredSize(new java.awt.Dimension(200, 0));
        jPanelRight.setLayout(new java.awt.GridBagLayout());

        btnHome.setText("HOME");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 10);
        jPanelRight.add(btnHome, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 1.0;
        jPanelRight.add(filler1, gridBagConstraints);

        btnEditProduct.setText("Editar Producto");
        btnEditProduct.addActionListener(this::btnEditProductActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 10);
        jPanelRight.add(btnEditProduct, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.weighty = 1.0;
        jPanelRight.add(filler2, gridBagConstraints);

        btnDeleteProduct.setText("Borrar Producto");
        btnDeleteProduct.addActionListener(this::btnDeleteProductActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 10);
        jPanelRight.add(btnDeleteProduct, gridBagConstraints);

        add(jPanelRight, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
// 1. Crear el panel de creación
        PanelCrearProducto pnlCrear = new PanelCrearProducto();

        // 2. Preparar el cambio de pantalla
        javax.swing.JPanel parent = (javax.swing.JPanel) getParent();
        java.awt.event.ActionListener[] listenersHome = btnHome.getActionListeners();

        // 3. Configurar el botón "Volver" del nuevo panel
        pnlCrear.getBtnBack().addActionListener(e -> {
            parent.removeAll();

            // Al volver, recreamos el panel de listado para ver los cambios
            PanelProductos nuevoListado = new PanelProductos();

            // Recuperamos la funcionalidad del botón Home
            if (listenersHome != null) {
                for (java.awt.event.ActionListener al : listenersHome) {
                    nuevoListado.getBtnHome().addActionListener(al);
                }
            }

            parent.add(nuevoListado, java.awt.BorderLayout.CENTER);
            parent.revalidate();
            parent.repaint();
        });

        // 4. Cambiar la vista
        parent.removeAll();
        parent.add(pnlCrear, java.awt.BorderLayout.CENTER);
        parent.revalidate();
        parent.repaint();    }//GEN-LAST:event_btnAddProductActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        cargarProductos(txtSearch.getText());
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProductActionPerformed
        borrarProductoSeleccionado();
    }//GEN-LAST:event_btnDeleteProductActionPerformed

    private void btnEditProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProductActionPerformed
        int fila = tblProducts.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un producto.");
            return;
        }

        // --- CORRECCIÓN AQUÍ ---
        // 1. Antes leíamos un INT (ID). Ahora leemos un STRING (CÓDIGO).
        String codigo = tblProducts.getValueAt(fila, 0).toString();

        // 2. Usamos el nuevo método del DAO para recuperar el objeto completo
        Producto p = productoDAO.buscarPorCodigo(codigo);

        if (p == null) {
            JOptionPane.showMessageDialog(this, "Error: No se encontró el producto en la base de datos.");
            return;
        }

        // 3. Pasamos el producto al constructor de edición
        PanelCrearProducto pnlEditar = new PanelCrearProducto(p);

        // --- NAVEGACIÓN (Esto lo tenías bien, se mantiene igual) ---
        javax.swing.JPanel parent = (javax.swing.JPanel) getParent();
        java.awt.event.ActionListener[] listenersHome = btnHome.getActionListeners();

        pnlEditar.getBtnBack().addActionListener(e -> {
            parent.removeAll();
            PanelProductos nuevoListado = new PanelProductos();
            if (listenersHome != null) {
                for (java.awt.event.ActionListener al : listenersHome) {
                    nuevoListado.getBtnHome().addActionListener(al);
                }
            }
            parent.add(nuevoListado, java.awt.BorderLayout.CENTER);
            parent.revalidate();
            parent.repaint();
        });

        parent.removeAll();
        parent.add(pnlEditar, java.awt.BorderLayout.CENTER);
        parent.revalidate();
        parent.repaint();
    }//GEN-LAST:event_btnEditProductActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // 1. Obtener texto
        String texto = txtSearch.getText().trim();

        // Seguridad por si el sorter no se inició
        if (sorter == null) {
            return;
        }

        // 2. Filtrar visualmente (sin ir a la base de datos)
        if (texto.length() == 0) {
            sorter.setRowFilter(null); // Mostrar todo
        } else {
            try {
                // (?i) ignora mayúsculas/minúsculas y busca en CUALQUIER columna
                sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + texto));
            } catch (Exception e) {
                // Ignorar errores de caracteres especiales
            }
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void setIconoBlanco(javax.swing.JButton btn, String rutaSvg) {
        com.formdev.flatlaf.extras.FlatSVGIcon icon = new com.formdev.flatlaf.extras.FlatSVGIcon(rutaSvg, 20, 20);
        // ESTO ES LA MAGIA: Fuerza el color blanco
        icon.setColorFilter(new com.formdev.flatlaf.extras.FlatSVGIcon.ColorFilter(color -> java.awt.Color.WHITE));
        btn.setIcon(icon);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnDeleteProduct;
    private javax.swing.JButton btnEditProduct;
    private javax.swing.JButton btnHome;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JScrollPane jScrollPaneCenter;
    private javax.swing.JTable tblProducts;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    // Método puente para acceder al botón Home desde fuera
    public javax.swing.JButton getBtnHome() {
        return btnHome;
    }

    // --- CARGAR PRODUCTOS EN LA TABLA ---
    private void cargarProductos(String busqueda) {
        List<Producto> lista;
        if (busqueda == null || busqueda.trim().isEmpty()) {
            lista = productoDAO.listarTodos();
        } else {
            lista = productoDAO.buscarPorTermino(busqueda);
        }

        DefaultTableModel modelo = (DefaultTableModel) tblProducts.getModel();
        modelo.setRowCount(0);

        for (Producto p : lista) {
            modelo.addRow(new Object[]{
                // CORRECCIÓN: Quitamos el ID oculto. Ponemos los datos en orden visual exacto.
                p.getCode(), // Col 0: Código
                p.getDescription(), // Col 1: Descripción
                p.getUnitPrice() + " €", // Col 2: Precio
                p.getTaxPercent() + " %" // Col 3: Tipo IVA
            });
        }

        sorter = new javax.swing.table.TableRowSorter<>(modelo);
        tblProducts.setRowSorter(sorter);
    }

    // --- BORRAR PRODUCTO ---
    private void borrarProductoSeleccionado() {
        int fila = tblProducts.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un producto para borrar.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "¿Seguro que quieres borrar este producto?",
                "Confirmar", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                // ID está en la columna 0
                String codigo = tblProducts.getValueAt(fila, 0).toString();

                // Llamada al DAO
                Producto p = productoDAO.buscarPorCodigo(codigo);
                if (p != null) {
                    productoDAO.eliminar(p.getId());
                }

                // Recargar
                cargarProductos(txtSearch.getText());

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al borrar: " + e.getMessage());
            }
        }
    }
}
