/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.interfaz;

/**
 *
 * @author DavidCe
 */
public class PanelFacturas extends javax.swing.JPanel {

    /**
     * Creates new form PanelClientes
     */
    public PanelFacturas() {
        initComponents();

        // --- 1. TABLA
        // --- APLICAR ESTILO A LA TABLA ---
        Estilos.configurarTabla(tblInvoices, jScrollPaneCenter);

        // --- DEFINIR ANCHOS DE COLUMNAS ---
// --- DEFINIR ANCHOS DE COLUMNAS (Total aprox: 800-900px) ---
        // 0. Nº Factura
        tblInvoices.getColumnModel().getColumn(0).setPreferredWidth(90);
        tblInvoices.getColumnModel().getColumn(0).setMaxWidth(100);

        // 1. Cliente (Le damos un poco más de espacio)
        tblInvoices.getColumnModel().getColumn(1).setPreferredWidth(180);

        // 2. Descripción (Reducimos un poco porque ya no tiene la fecha dentro)
        tblInvoices.getColumnModel().getColumn(2).setPreferredWidth(200);

        // 3. Estado
        tblInvoices.getColumnModel().getColumn(3).setPreferredWidth(80);

        // 4. Total
        tblInvoices.getColumnModel().getColumn(4).setPreferredWidth(80);

        // 5. Fecha Emisión
        tblInvoices.getColumnModel().getColumn(5).setPreferredWidth(120);

        // Bloquear reordenamiento
        tblInvoices.getTableHeader().setReorderingAllowed(false);

        // --- 2. BARRA DE BÚSQUEDA
        // --- APLICAR ESTILO A LA BARRA DE BÚSQUEDA ---
        Estilos.configurarBarraBusqueda(txtSearch);
        txtSearch.putClientProperty(com.formdev.flatlaf.FlatClientProperties.PLACEHOLDER_TEXT, "Buscar Factura por Nº");

        // --- 3. BOTONES
        // --- APLICAR ESTILO A LOS BOTONES ---
        // Creamos una lista con todos los botones para aplicarles el estilo "Píldora Negra" de golpe
        javax.swing.JButton[] botonesAccion = {
            btnCreateInvoice, // Añadir Cliente
            btnInvoiceDetails, // Editar
            btnVerifyAEAT // Borrar
        };

        for (javax.swing.JButton btn : botonesAccion) {
            Estilos.configurarBotonAccion(btn);
        }

        // Botón Home como Icono
        com.formdev.flatlaf.extras.FlatSVGIcon homeIcon = new com.formdev.flatlaf.extras.FlatSVGIcon("img/home_Icon.svg", 32, 32);
        // Usamos Color.BLACK (o Color.decode("#111111") para negro suave)
        homeIcon.setColorFilter(new com.formdev.flatlaf.extras.FlatSVGIcon.ColorFilter(color -> java.awt.Color.BLACK));
        btnHome.setIcon(homeIcon);
        btnHome.setText("");
        // Estilo "invisible" para que solo se vea el icono
        btnHome.setContentAreaFilled(false);
        btnHome.setBorderPainted(false);
        btnHome.setFocusPainted(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        // Añadir icono a los botones
        setIconoBlanco(btnInvoiceDetails, "img/details_Icon.svg");
        setIconoBlanco(btnVerifyAEAT, "img/check_Icon.svg");

        // --- CONFIGURACIÓN BOTÓN CREAR FACTURA ---
        // 1. Cargar el icono SVG (Tamaño 20x20)
        com.formdev.flatlaf.extras.FlatSVGIcon iconAdd = new com.formdev.flatlaf.extras.FlatSVGIcon("img/add_Icon.svg", 20, 20);

        // 2. Pintarlo de BLANCO (porque el botón es negro)
        iconAdd.setColorFilter(new com.formdev.flatlaf.extras.FlatSVGIcon.ColorFilter(c -> java.awt.Color.WHITE));

        // 3. Asignarlo al botón
        btnCreateInvoice.setIcon(iconAdd);

        // 4. Ajustes visuales
        btnCreateInvoice.setIconTextGap(10); // Espacio entre el (+) y el texto
        btnCreateInvoice.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT); // Texto a la derecha del icono

        // Asegurarnos de que el texto esté centrado verticalmente
        btnCreateInvoice.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);

        // Ajustes finales de texto y márgenes
        javax.swing.JButton[] botones = {btnInvoiceDetails, btnVerifyAEAT};
        for (javax.swing.JButton btn : botones) {
            btn.setIconTextGap(15);
            btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            // Ajusta este margen si quieres los botones más o menos anchos
            btn.setMargin(new java.awt.Insets(10, 15, 10, 15));
        }

        // --- 4. CARGAR DATOS DE FACTURAS DE LA BASE DE DATOS ---
        cargarTablaFacturas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelCenter = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnCreateInvoice = new javax.swing.JButton();
        jScrollPaneCenter = new javax.swing.JScrollPane();
        tblInvoices = new javax.swing.JTable();
        jPanelRight = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnInvoiceDetails = new javax.swing.JButton();
        btnVerifyAEAT = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setBackground(new java.awt.Color(160, 238, 204));
        setLayout(new java.awt.BorderLayout());

        jPanelCenter.setBackground(new java.awt.Color(160, 238, 204));
        jPanelCenter.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelCenter.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 15, 10);
        jPanelCenter.add(txtSearch, gridBagConstraints);

        btnCreateInvoice.setText("Crear Factura");
        btnCreateInvoice.addActionListener(this::btnCreateInvoiceActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 15, 10);
        jPanelCenter.add(btnCreateInvoice, gridBagConstraints);

        jScrollPaneCenter.setOpaque(false);

        tblInvoices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nº", "Cliente", "Descripción", "Estado", "Total Factura", "Fecha emisión"
            }
        ));
        jScrollPaneCenter.setViewportView(tblInvoices);
        if (tblInvoices.getColumnModel().getColumnCount() > 0) {
            tblInvoices.getColumnModel().getColumn(0).setResizable(false);
            tblInvoices.getColumnModel().getColumn(1).setResizable(false);
            tblInvoices.getColumnModel().getColumn(2).setResizable(false);
            tblInvoices.getColumnModel().getColumn(3).setResizable(false);
            tblInvoices.getColumnModel().getColumn(4).setResizable(false);
            tblInvoices.getColumnModel().getColumn(5).setResizable(false);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelCenter.add(jScrollPaneCenter, gridBagConstraints);

        add(jPanelCenter, java.awt.BorderLayout.CENTER);

        jPanelRight.setOpaque(false);
        jPanelRight.setPreferredSize(new java.awt.Dimension(200, 0));
        jPanelRight.setLayout(new java.awt.GridBagLayout());

        btnHome.setText("HOME");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 10);
        jPanelRight.add(btnHome, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 1.0;
        jPanelRight.add(filler1, gridBagConstraints);

        btnInvoiceDetails.setText("Datos Factura");
        btnInvoiceDetails.addActionListener(this::btnInvoiceDetailsActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 10);
        jPanelRight.add(btnInvoiceDetails, gridBagConstraints);

        btnVerifyAEAT.setText("Verificar AEAT");
        btnVerifyAEAT.addActionListener(this::btnVerifyAEATActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 10);
        jPanelRight.add(btnVerifyAEAT, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weighty = 1.0;
        jPanelRight.add(filler2, gridBagConstraints);

        add(jPanelRight, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateInvoiceActionPerformed
        // 1. Obtener la ventana principal (JFrame) para que sea el "padre" del diálogo
        // Esto es necesario para que el diálogo sepa centrarse y bloquear la ventana de atrás (modal)
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        java.awt.Frame parentFrame = null;

        if (parentWindow instanceof java.awt.Frame) {
            parentFrame = (java.awt.Frame) parentWindow;
        }

        // 2. Crear el Diálogo (true = modal, bloquea la ventana de atrás)
        DialogCrearFactura dialog = new DialogCrearFactura(parentFrame, true);

        // 3. Mostrarlo
        // El código se detendrá aquí hasta que el usuario cierre el diálogo
        dialog.setVisible(true);

        // AL VOLVER DEL DIÁLOGO, REFRESCAMOS:
        cargarTablaFacturas();
    }//GEN-LAST:event_btnCreateInvoiceActionPerformed

    private void btnInvoiceDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvoiceDetailsActionPerformed
        // 1. Verificar si hay una fila seleccionada
        int selectedRow = tblInvoices.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor, selecciona una factura de la tabla primero.",
                    "Atención", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Obtener el número de la factura de la columna 0 (Ej: "F-0004")
        String numeroCompleto = (String) tblInvoices.getValueAt(selectedRow, 0);

        try {
            // Desglosamos "F-0004" en "F" y "4"
            String[] partes = numeroCompleto.split("-");
            String serie = partes[0];
            int numero = Integer.parseInt(partes[1]);

            // 3. Recuperar la factura completa de la BBDD
            com.mycompany.dao.FacturaDAO dao = new com.mycompany.dao.FacturaDAO();
            com.mycompany.dominio.Factura factura = dao.obtenerPorSerieYNumero(serie, numero);

            if (factura != null) {
                // 4. Verificar si tiene PDF guardado
                String pdfBase64 = factura.getPdfFactura();

                if (pdfBase64 != null && !pdfBase64.isEmpty() && !pdfBase64.startsWith("ERROR")) {

                    // --- PROCESO DE APERTURA DEL PDF ---
                    try {
                        // A. Decodificar de Base64 a Bytes
                        byte[] pdfBytes = java.util.Base64.getDecoder().decode(pdfBase64);

                        // B. Crear un archivo temporal en el ordenador
                        // (Los visores de PDF necesitan un archivo físico para abrirse)
                        java.io.File tempFile = java.io.File.createTempFile("Factura_" + numeroCompleto + "_", ".pdf");
                        tempFile.deleteOnExit(); // Se borrará al cerrar el programa java (opcional)

                        // C. Escribir los bytes en el archivo
                        java.nio.file.Files.write(tempFile.toPath(), pdfBytes);

                        // D. Abrir con el visor por defecto del sistema
                        if (java.awt.Desktop.isDesktopSupported()) {
                            java.awt.Desktop.getDesktop().open(tempFile);
                        } else {
                            javax.swing.JOptionPane.showMessageDialog(this, "El sistema no soporta abrir archivos automáticamente.");
                        }

                    } catch (Exception ex) {
                        ex.printStackTrace();
                        javax.swing.JOptionPane.showMessageDialog(this, "Error al abrir el PDF: " + ex.getMessage());
                    }

                } else {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Esta factura no tiene un PDF almacenado en la base de datos.",
                            "Sin PDF", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error al recuperar datos: " + e.getMessage());
        }
    }//GEN-LAST:event_btnInvoiceDetailsActionPerformed

    private void btnVerifyAEATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyAEATActionPerformed
        // 1. Obtener la fila seleccionada
        int fila = tblInvoices.getSelectedRow();

        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor, selecciona una factura de la lista para verificar.",
                    "Selección requerida",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // 2. Obtener datos de la tabla
            // Columna 0: Nº (Ej: "F-0011")
            // Columna 4: Total Factura (Ej: "363,00 €")
            // Columna 5: Fecha emisión (Ej: "07/01/2026 06:59")

            Object objNum = tblInvoices.getValueAt(fila, 0);
            Object objTotal = tblInvoices.getValueAt(fila, 4);
            Object objFecha = tblInvoices.getValueAt(fila, 5);

            if (objNum == null || objTotal == null || objFecha == null) {
                return; // Evitar nulos
            }

            String numSerie = objNum.toString();
            String totalTexto = objTotal.toString();
            String fechaTexto = objFecha.toString();

            // 3. Formatear datos para la URL (Parsing)
            // A. IMPORTE: De "363,00 €" a "363.00"
            // Quitamos '€', espacios y cambiamos la coma decimal por punto
            String importeLimpio = totalTexto.replace("€", "")
                    .replace(" ", "")
                    .trim()
                    .replace(",", ".");

            // B. FECHA: De "07/01/2026 06:59" a "07-01-2026"
            // Nos quedamos con los primeros 10 caracteres y cambiamos barras por guiones
            String fechaCorta = fechaTexto.substring(0, 10).replace("/", "-");

            // C. NIF: Usamos el que has pasado en el ejemplo (NIF del Emisor se configura desde Fiskaly y se obtiene con el token de autenticación)
            String nifEmisor = "18053094A";

            // 4. Construir la URL
            // https://prewww2.aeat.es/wlpl/TIKE-CONT/ValidarQR?nif=...&numserie=...&fecha=...&importe=...
            String urlBase = "https://prewww2.aeat.es/wlpl/TIKE-CONT/ValidarQR";
            String urlFinal = String.format("%s?nif=%s&numserie=%s&fecha=%s&importe=%s",
                    urlBase, nifEmisor, numSerie, fechaCorta, importeLimpio);

            System.out.println("Verificando en AEAT: " + urlFinal); // Log para consola

            // 5. Abrir en el navegador predeterminado
            if (java.awt.Desktop.isDesktopSupported() && java.awt.Desktop.getDesktop().isSupported(java.awt.Desktop.Action.BROWSE)) {
                java.awt.Desktop.getDesktop().browse(new java.net.URI(urlFinal));
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Tu sistema no soporta abrir navegadores automáticamente.");
            }

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al intentar abrir la web de la AEAT:\n" + e.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnVerifyAEATActionPerformed

    private void setIconoBlanco(javax.swing.JButton btn, String rutaSvg) {
        com.formdev.flatlaf.extras.FlatSVGIcon icon = new com.formdev.flatlaf.extras.FlatSVGIcon(rutaSvg, 20, 20);
        // Fuerza el color blanco
        icon.setColorFilter(new com.formdev.flatlaf.extras.FlatSVGIcon.ColorFilter(color -> java.awt.Color.WHITE));
        btn.setIcon(icon);
    }

    // MÉTODO PARA CARGAR LAS FACTURAS
    public void cargarTablaFacturas() {
        // 1. Limpiar la tabla actual
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblInvoices.getModel();
        model.setRowCount(0);

        // 2. Obtener datos
        com.mycompany.dao.FacturaDAO dao = new com.mycompany.dao.FacturaDAO();
        java.util.List<com.mycompany.dominio.Factura> lista = dao.listarTodas();

        java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

        // 3. Rellenar filas
        for (com.mycompany.dominio.Factura f : lista) {

            // A. Nº Factura
            String numeroFormateado = f.getSeries() + "-" + String.format("%04d", f.getNumber());

            // B. Cliente
            String nombreCliente = "Desconocido";
            if (f.getCliente() != null) {
                nombreCliente = f.getCliente().getFiscalName();
            }

            // C. Descripción
            String descripcion = "FACTURA GENERAL";
            if (f.getSeries() != null) {
                if (f.getSeries().equalsIgnoreCase("F")) {
                    descripcion = "FACTURA COMPLETA";
                } else if (f.getSeries().equalsIgnoreCase("R")) {
                    descripcion = "FACTURA RECTIFICATIVA";
                }
            }

            // D. Estado (CAMBIO SOLICITADO)
            String estado = "PENDIENTE";
            // Si hay UUID, consideramos que está enviada correctamente
            if (f.getFiskalyUuid() != null && !f.getFiskalyUuid().isEmpty()) {
                estado = "ENVIADA";
            }

            // E. Fecha de Emisión (NUEVA COLUMNA)
            String fechaTexto = "";
            if (f.getDate() != null) {
                fechaTexto = f.getDate().format(formatter);
            } else if (f.getCreatedAt() != null) {
                // Fallback por si date es nulo (usamos created_at)
                fechaTexto = f.getCreatedAt().format(formatter);
            }

            // F. Añadir fila (AHORA CON 6 ELEMENTOS)
            model.addRow(new Object[]{
                numeroFormateado, // 0. Nº
                nombreCliente, // 1. Cliente
                descripcion, // 2. Descripción
                estado, // 3. Estado (ENVIADA / PENDIENTE)
                String.format("%.2f €", f.getTotalAmount()), // 4. Total
                fechaTexto // 5. Fecha Emisión
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateInvoice;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnInvoiceDetails;
    private javax.swing.JButton btnVerifyAEAT;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JScrollPane jScrollPaneCenter;
    private javax.swing.JTable tblInvoices;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    // Método puente para acceder al botón Home desde fuera
    public javax.swing.JButton getBtnHome() {
        return btnHome;
    }
}
