/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.interfaz;

import com.mycompany.fiskaly.Clients;
import com.mycompany.fiskaly.Config;
import com.mycompany.fiskaly.Signers;

/**
 *
 * @author DavidCe
 */
public class PanelConfig extends javax.swing.JPanel {

    /**
     * Creates new form PanelClientes
     */
    public PanelConfig() {
        initComponents();

        // --- 1. BOTONES
        // --- APLICAR ESTILO A LOS BOTONES ---
        // Creamos una lista con todos los botones para aplicarles el estilo "Píldora Negra" de golpe
        javax.swing.JButton[] botonesAccion = {
            btnDashboardFiskaly,
            btnAPIKey,
            btnTaxpayer,
            btnClientFiskaly,
            btnAddUser,
            btnEditUser,
            btnDeleteUser
        };

        for (javax.swing.JButton btn : botonesAccion) {
            Estilos.configurarBotonAccion(btn);
        }

        // Botón Home como Icono
        com.formdev.flatlaf.extras.FlatSVGIcon homeIcon = new com.formdev.flatlaf.extras.FlatSVGIcon("img/home_Icon.svg", 32, 32);
        // Usamos Color.BLACK (o Color.decode("#111111") para negro suave)
        homeIcon.setColorFilter(new com.formdev.flatlaf.extras.FlatSVGIcon.ColorFilter(color -> java.awt.Color.BLACK));
        btnHome.setIcon(homeIcon);
        btnHome.setText("");
        // Estilo "invisible" para que solo se vea el icono
        btnHome.setContentAreaFilled(false);
        btnHome.setBorderPainted(false);
        btnHome.setFocusPainted(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        // Añadir icono a los botones
        setIconoBlanco(btnDashboardFiskaly, "img/globe.svg");
        setIconoBlanco(btnAPIKey, "img/key.svg");
        setIconoBlanco(btnTaxpayer, "img/taxpayer.svg");
        setIconoBlanco(btnClientFiskaly, "img/keyboard.svg");
        setIconoBlanco(btnAddUser, "img/user_add.svg");
        setIconoBlanco(btnEditUser, "img/user_edit.svg");
        setIconoBlanco(btnDeleteUser, "img/user_delete.svg");

        // Ajustes finales de texto y márgenes
        javax.swing.JButton[] botones = {btnDashboardFiskaly, btnAPIKey, btnTaxpayer, btnClientFiskaly};
        for (javax.swing.JButton btn : botones) {
            btn.setIconTextGap(15);
            btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            btn.setMargin(new java.awt.Insets(10, 15, 10, 15));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelCenter = new javax.swing.JPanel();
        iconFiskaly = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnDashboardFiskaly = new javax.swing.JButton();
        btnTaxpayer = new javax.swing.JButton();
        btnClientFiskaly = new javax.swing.JButton();
        btnAPIKey = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanelRight = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnAddUser = new javax.swing.JButton();
        btnEditUser = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setBackground(new java.awt.Color(160, 238, 204));
        setLayout(new java.awt.BorderLayout());

        jPanelCenter.setBackground(new java.awt.Color(160, 238, 204));
        jPanelCenter.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelCenter.setLayout(new java.awt.GridBagLayout());

        iconFiskaly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fiskaly_negro.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanelCenter.add(iconFiskaly, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 1.0;
        jPanelCenter.add(filler4, gridBagConstraints);

        btnDashboardFiskaly.setText("Dashboard Fiskaly");
        btnDashboardFiskaly.addActionListener(this::btnDashboardFiskalyActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 15, 0);
        jPanelCenter.add(btnDashboardFiskaly, gridBagConstraints);

        btnTaxpayer.setText("Crear Dispositivo Firmante");
        btnTaxpayer.addActionListener(this::btnTaxpayerActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 15, 0);
        jPanelCenter.add(btnTaxpayer, gridBagConstraints);

        btnClientFiskaly.setText("Crear Dispositivo Cliente");
        btnClientFiskaly.addActionListener(this::btnClientFiskalyActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 15, 0);
        jPanelCenter.add(btnClientFiskaly, gridBagConstraints);

        btnAPIKey.setText("Cambiar API Key");
        btnAPIKey.addActionListener(this::btnAPIKeyActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 15, 0);
        jPanelCenter.add(btnAPIKey, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.weighty = 1.0;
        jPanelCenter.add(filler3, gridBagConstraints);

        add(jPanelCenter, java.awt.BorderLayout.CENTER);

        jPanelRight.setOpaque(false);
        jPanelRight.setPreferredSize(new java.awt.Dimension(200, 0));
        jPanelRight.setLayout(new java.awt.GridBagLayout());

        btnHome.setText("HOME");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 10);
        jPanelRight.add(btnHome, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 0.5;
        jPanelRight.add(filler1, gridBagConstraints);

        btnAddUser.setText("Crear Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 10);
        jPanelRight.add(btnAddUser, gridBagConstraints);

        btnEditUser.setText("Editar Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 10);
        jPanelRight.add(btnEditUser, gridBagConstraints);

        btnDeleteUser.setText("Borrar Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 10);
        jPanelRight.add(btnDeleteUser, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weighty = 1.0;
        jPanelRight.add(filler2, gridBagConstraints);

        add(jPanelRight, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientFiskalyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientFiskalyActionPerformed
        // Ejecutamos la llamada a la API en un hilo separado
        new Thread(() -> {
            try {
                Config.refrescarUUID();// importante para obtener un nuevo UUID
                
                // 1. Llamamos al método y esperamos que devuelva el código (int)
                // Asegúrate de que tu método Clients.createClient() devuelve 'int'
                int statusCode = Clients.createClient();

                // 2. Volvemos al hilo de la interfaz (EDT) para mostrar el mensaje
                javax.swing.SwingUtilities.invokeLater(() -> {
                    if (statusCode == 200 || statusCode == 201) {
                        javax.swing.JOptionPane.showMessageDialog(this,
                                "¡Dispositivo Cliente (TSS) creado con éxito!\n",
                                "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this,
                                "Error al crear el cliente.\nCódigo de respuesta: " + statusCode,
                                "Error API", javax.swing.JOptionPane.ERROR_MESSAGE);
                    }
                });

            } catch (Exception e) {
                e.printStackTrace();
                javax.swing.SwingUtilities.invokeLater(() -> {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Ocurrió un error de conexión: " + e.getMessage(),
                            "Error Crítico", javax.swing.JOptionPane.ERROR_MESSAGE);
                });
            }
        }).start();
    }//GEN-LAST:event_btnClientFiskalyActionPerformed

    private void btnDashboardFiskalyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardFiskalyActionPerformed
        abrirURL("https://dashboard.fiskaly.com");
    }//GEN-LAST:event_btnDashboardFiskalyActionPerformed

    private void btnAPIKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAPIKeyActionPerformed
        abrirDialogoCredenciales();
    }//GEN-LAST:event_btnAPIKeyActionPerformed

    private void btnTaxpayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaxpayerActionPerformed
        // Ejecutamos la llamada a la API en un hilo separado
        new Thread(() -> {
            try {
                Config.refrescarUUID();// importante para obtener un nuevo UUID

                // 1. Llamamos al método y esperamos que devuelva el código (int)
                int statusCode = Signers.createSigner();

                // 2. Volvemos al hilo de la interfaz (EDT) para mostrar el mensaje
                javax.swing.SwingUtilities.invokeLater(() -> {
                    if (statusCode == 200 || statusCode == 201) {
                        javax.swing.JOptionPane.showMessageDialog(this,
                                "¡Dispositivo Firmante creado con éxito!\n",
                                "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this,
                                "Error al crear el firmante.\nCódigo de respuesta: " + statusCode,
                                "Error API", javax.swing.JOptionPane.ERROR_MESSAGE);
                    }
                });

            } catch (Exception e) {
                e.printStackTrace();
                javax.swing.SwingUtilities.invokeLater(() -> {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Ocurrió un error de conexión: " + e.getMessage(),
                            "Error Crítico", javax.swing.JOptionPane.ERROR_MESSAGE);
                });
            }
        }).start();
    }//GEN-LAST:event_btnTaxpayerActionPerformed

    private void setIconoBlanco(javax.swing.JButton btn, String rutaSvg) {
        com.formdev.flatlaf.extras.FlatSVGIcon icon = new com.formdev.flatlaf.extras.FlatSVGIcon(rutaSvg, 20, 20);
        // Fuerza el color blanco
        icon.setColorFilter(new com.formdev.flatlaf.extras.FlatSVGIcon.ColorFilter(color -> java.awt.Color.WHITE));
        btn.setIcon(icon);
    }

    private void abrirURL(String url) {
        try {
            // 1. Verificar si el sistema soporta la clase Desktop
            if (java.awt.Desktop.isDesktopSupported()) {
                java.awt.Desktop desktop = java.awt.Desktop.getDesktop();

                // 2. Verificar si soporta la acción de abrir navegador
                if (desktop.isSupported(java.awt.Desktop.Action.BROWSE)) {
                    // 3. Abrir la URL
                    desktop.browse(new java.net.URI(url));
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Tu sistema no permite abrir navegadores automáticamente.",
                            "Error", javax.swing.JOptionPane.WARNING_MESSAGE);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al intentar abrir el enlace:\n" + e.getMessage(),
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void abrirDialogoCredenciales() {
        // 1. Campos de texto rellenos con lo que haya actualmente
        javax.swing.JTextField txtApiKey = new javax.swing.JTextField(com.mycompany.fiskaly.Config.API_KEY);
        javax.swing.JPasswordField txtApiSecret = new javax.swing.JPasswordField(com.mycompany.fiskaly.Config.API_SECRET);

        // 2. Panel visual
        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.GridLayout(0, 1, 5, 5));
        panel.add(new javax.swing.JLabel("Introduce tu API Key de Fiskaly:"));
        panel.add(txtApiKey);
        panel.add(new javax.swing.JLabel("Introduce tu API Secret:"));
        panel.add(txtApiSecret);

        // Checkbox opcional para ver la contraseña
        javax.swing.JCheckBox chkVer = new javax.swing.JCheckBox("Mostrar Secret");
        chkVer.addActionListener(e -> {
            txtApiSecret.setEchoChar(chkVer.isSelected() ? (char) 0 : '•');
        });
        panel.add(chkVer);

        // 3. Mostrar Diálogo
        int resultado = javax.swing.JOptionPane.showConfirmDialog(this, panel,
                "Configuración Persistente Fiskaly",
                javax.swing.JOptionPane.OK_CANCEL_OPTION,
                javax.swing.JOptionPane.PLAIN_MESSAGE);

        // 4. Guardar
        if (resultado == javax.swing.JOptionPane.OK_OPTION) {
            String nuevaKey = txtApiKey.getText().trim();
            String nuevoSecret = new String(txtApiSecret.getPassword()).trim();

            if (!nuevaKey.isEmpty() && !nuevoSecret.isEmpty()) {

                // Llamamos al método que guarda en RAM y en DISCO
                Config.guardarCredenciales(nuevaKey, nuevoSecret);

                javax.swing.JOptionPane.showMessageDialog(this,
                        "¡Guardado! Las credenciales se recordarán la próxima vez que abras la app.");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "No se han guardado cambios (campos vacíos).",
                        "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAPIKey;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnClientFiskaly;
    private javax.swing.JButton btnDashboardFiskaly;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnEditUser;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnTaxpayer;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JLabel iconFiskaly;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelRight;
    // End of variables declaration//GEN-END:variables

    // Método puente para acceder al botón Home desde fuera
    public javax.swing.JButton getBtnHome() {
        return btnHome;
    }
}
